/**
 * 다국어 설정 및 번역 관리
 * 새로운 언어 추가: 여기에만 추가하면 자동으로 반영됨
 */

export type LanguageCode = 'en' | 'ko' | 'ja' | 'zh' | 'de' | 'fr' | 'es' | 'it' | 'ru';

export const LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
];

export interface TranslationStrings {
  app_name: string;
  app_sub: string;
  app_desc: string;
  hero_badge: string;
  hero_title: string;
  hero_highlight: string;
  hero_desc: string;
  label_industry: string;
  label_upload: string;
  tab_file: string;
  tab_text: string;
  drop_title: string;
  drop_desc: string;
  text_placeholder: string;
  btn_analyze: string;
  analyzing_title: string;
  report_title: string;
  report_date: string;
  overall_rating: string;
  exec_summary: string;
  factor_analysis: string;
  expert_commentary: string;
  roadmap: string;
  download_btn: string;
  generating: string;
  reset_btn: string;
  disclaimer: string;
  industries: Record<string, string>;
  comments: {
    tech: string;
    market: string;
    fin: string;
    risk: string;
  };
}

export const TRANSLATIONS: Record<LanguageCode, TranslationStrings> = {
  en: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strategic Business Assessment Tool",
    hero_badge: "Professional Due Diligence",
    hero_title: "Business Feasibility",
    hero_highlight: "Intelligence Report",
    hero_desc: "Get consistent, objective evaluations. We set the AI temperature to 0.0 for reliable, repeatable scoring based on strict McKinsey-style rubrics.",
    label_industry: "1. Select Industry Sector",
    label_upload: "2. Upload Document",
    tab_file: "File Upload",
    tab_text: "Direct Text",
    drop_title: "Drop your Business Plan here",
    drop_desc: "Supports PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Paste the core content of your business plan here...",
    btn_analyze: "Generate Expert Report",
    analyzing_title: "Analyzing Business Plan",
    report_title: "Confidential Feasibility Report",
    report_date: "Date",
    overall_rating: "Overall Rating",
    exec_summary: "Executive Summary",
    factor_analysis: "5-Factor Strategic Analysis",
    expert_commentary: "Expert Commentary",
    roadmap: "Strategic Roadmap & Action Plan",
    download_btn: "Download Report",
    generating: "Generating...",
    reset_btn: "Reset",
    disclaimer: "Generated by FS Pro | Temperature 0.0 (Deterministic Mode)",
    industries: {
      'AI/Data': 'AI & Data',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Health',
      'Clean Energy': 'Clean Energy',
      'Aerospace/Manufacturing': 'Manufacturing',
      'Content/Media': 'Content/Media',
      'Civil/Construction': 'Civil/Construction',
      'General/Other': 'General'
    },
    comments: {
      tech: "Technical Due Diligence",
      market: "Market Strategy",
      fin: "Financial Projection",
      risk: "Risk & Compliance"
    }
  },
  ko: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "전략적 사업성 평가 솔루션",
    hero_badge: "전문가급 기업 실사(Due Diligence)",
    hero_title: "사업 타당성 분석",
    hero_highlight: "인텔리전스 리포트",
    hero_desc: "AI의 창의성 변수(Temperature)를 0으로 제어하여, 언제나 일관성 있고 객관적인 정량 평가 결과를 제공합니다.",
    label_industry: "1. 산업 분야 선택",
    label_upload: "2. 문서 업로드",
    tab_file: "파일 업로드",
    tab_text: "텍스트 입력",
    drop_title: "사업계획서 파일을 이곳에 놓으세요",
    drop_desc: "PDF, TXT, MD 지원 (최대 10MB)",
    text_placeholder: "사업계획서의 핵심 내용을 이곳에 붙여넣으세요...",
    btn_analyze: "전문가 분석 리포트 생성",
    analyzing_title: "사업계획서 심층 분석 중",
    report_title: "사업성 평가 보고서 (대외비)",
    report_date: "평가일",
    overall_rating: "종합 평가 등급",
    exec_summary: "경영진 요약 (Executive Summary)",
    factor_analysis: "5대 핵심 요소 전략 분석",
    expert_commentary: "전문가 심층 코멘트",
    roadmap: "전략적 로드맵 및 실행 계획",
    download_btn: "리포트 다운로드",
    generating: "생성 중...",
    reset_btn: "새로운 분석",
    disclaimer: "FS Pro 생성 자료 | Temperature 0.0 (정밀 분석 모드)",
    industries: {
      'AI/Data': 'AI/데이터',
      'Blockchain/Fintech': '핀테크/블록체인',
      'Bio/Healthcare': '바이오/헬스',
      'Clean Energy': '클린 에너지',
      'Aerospace/Manufacturing': '제조/항공',
      'Content/Media': '콘텐츠/미디어',
      'Civil/Construction': '토목/건축',
      'General/Other': '일반/기타'
    },
    comments: {
      tech: "기술성 실사 (Tech DD)",
      market: "시장 진입 전략",
      fin: "재무 건전성 및 ROI",
      risk: "규제 및 리스크 관리"
    }
  },
  ja: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "戦略的事業性評価ツール",
    hero_badge: "プロフェッショナル・デューデリジェンス",
    hero_title: "事業妥当性分析",
    hero_highlight: "インテリジェンス・レポート",
    hero_desc: "AIの創造性パラメータ（Temperature）を0に設定し、常に一貫性のある客観的な定量評価結果を提供します。",
    label_industry: "1. 産業分野の選択",
    label_upload: "2. ドキュメントのアップロード",
    tab_file: "ファイル",
    tab_text: "テキスト入力",
    drop_title: "ここに事業計画書をドロップ",
    drop_desc: "PDF, TXT, MD 対応 (最大 10MB)",
    text_placeholder: "事業計画書の核心内容をここに貼り付けてください...",
    btn_analyze: "専門家レポートを作成",
    analyzing_title: "事業計画書を分析中",
    report_title: "事業性評価レポート (社外秘)",
    report_date: "日付",
    overall_rating: "総合評価",
    exec_summary: "エグゼクティブ・サマリー",
    factor_analysis: "5大要素 戦略分析",
    expert_commentary: "専門家の解説",
    roadmap: "戦略的ロードマップ & アクションプラン",
    download_btn: "レポートをダウンロード",
    generating: "作成中...",
    reset_btn: "リセット",
    disclaimer: "FS Proにより生成 | Temperature 0.0 (精密分析モード)",
    industries: {
      'AI/Data': 'AI/データ',
      'Blockchain/Fintech': 'フィンテック',
      'Bio/Healthcare': 'バイオ/ヘルス',
      'Clean Energy': 'クリーンエネ',
      'Aerospace/Manufacturing': '製造/航空',
      'Content/Media': 'コンテンツ',
      'Civil/Construction': '土木/建設',
      'General/Other': '一般/その他'
    },
    comments: {
      tech: "技術デューデリジェンス",
      market: "市場参入戦略",
      fin: "財務予測 & ROI",
      risk: "リスクとコンプライアンス"
    }
  },
  zh: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "战略商业评估工具",
    hero_badge: "专业尽职调查",
    hero_title: "商业可行性",
    hero_highlight: "智能分析报告",
    hero_desc: "将AI的创造性参数（Temperature）设置为0，以提供始终如一且客观的定量评估结果。",
    label_industry: "1. 选择行业领域",
    label_upload: "2. 上传文档",
    tab_file: "文件上传",
    tab_text: "直接输入",
    drop_title: "在此处拖放您的商业计划书",
    drop_desc: "支持 PDF, TXT, MD (最大 10MB)",
    text_placeholder: "在此粘贴商业计划书的核心内容...",
    btn_analyze: "生成专家报告",
    analyzing_title: "正在分析商业计划",
    report_title: "可行性评估报告 (机密)",
    report_date: "日期",
    overall_rating: "综合评分",
    exec_summary: "执行摘要 (Executive Summary)",
    factor_analysis: "五维战略分析",
    expert_commentary: "专家点评",
    roadmap: "战略路线图与行动计划",
    download_btn: "下载报告",
    generating: "生成中...",
    reset_btn: "重置",
    disclaimer: "由 FS Pro 生成 | Temperature 0.0 (精密分析模式)",
    industries: {
      'AI/Data': '人工智能/数据',
      'Blockchain/Fintech': '金融科技',
      'Bio/Healthcare': '生物医疗',
      'Clean Energy': '清洁能源',
      'Aerospace/Manufacturing': '制造/航空',
      'Content/Media': '内容/媒体',
      'Civil/Construction': '土木/建筑',
      'General/Other': '通用/其他'
    },
    comments: {
      tech: "技术尽职调查",
      market: "市场进入策略",
      fin: "财务预测与回报",
      risk: "风险与合规"
    }
  },
  de: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strategisches Geschäftsbewertungstool",
    hero_badge: "Professionelle Due Diligence",
    hero_title: "Geschäftliche Machbarkeit",
    hero_highlight: "Intelligenzbericht",
    hero_desc: "Wir setzen die AI-Temperatur auf 0,0, um konsistente und objektive quantitative Bewertungsergebnisse zu gewährleisten.",
    label_industry: "1. Industriezweig wählen",
    label_upload: "2. Dokument hochladen",
    tab_file: "Datei-Upload",
    tab_text: "Texteingabe",
    drop_title: "Businessplan hier ablegen",
    drop_desc: "Unterstützt PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Fügen Sie hier den Kerninhalt Ihres Businessplans ein...",
    btn_analyze: "Expertenbericht erstellen",
    analyzing_title: "Businessplan wird analysiert",
    report_title: "Vertraulicher Machbarkeitsbericht",
    report_date: "Datum",
    overall_rating: "Gesamtbewertung",
    exec_summary: "Management-Zusammenfassung",
    factor_analysis: "Strategische 5-Faktoren-Analyse",
    expert_commentary: "Expertenkommentar",
    roadmap: "Strategische Roadmap",
    download_btn: "Bericht herunterladen",
    generating: "Erzeugen...",
    reset_btn: "Zurücksetzen",
    disclaimer: "Generiert von FS Pro | Temperature 0.0 (Präzisionsmodus)",
    industries: {
      'AI/Data': 'KI/Daten',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Gesundheit',
      'Clean Energy': 'Saubere Energie',
      'Aerospace/Manufacturing': 'Fertigung',
      'Content/Media': 'Medien',
      'Civil/Construction': 'Bauwesen',
      'General/Other': 'Allgemein'
    },
    comments: {
      tech: "Technische Due Diligence",
      market: "Markteintrittsstrategie",
      fin: "Finanzprognose",
      risk: "Risiko & Compliance"
    }
  },
  fr: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Outil d'évaluation stratégique",
    hero_badge: "Due Diligence Professionnelle",
    hero_title: "Faisabilité Commerciale",
    hero_highlight: "Rapport d'Intelligence",
    hero_desc: "Nous réglons la température de l'IA sur 0,0 pour garantir des résultats d'évaluation quantitative cohérents et objectifs.",
    label_industry: "1. Sélectionner le secteur",
    label_upload: "2. Télécharger le document",
    tab_file: "Fichier",
    tab_text: "Texte",
    drop_title: "Déposez votre plan d'affaires ici",
    drop_desc: "Supporte PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Collez ici le contenu principal...",
    btn_analyze: "Générer le rapport",
    analyzing_title: "Analyse en cours",
    report_title: "Rapport de Faisabilité (Confidentiel)",
    report_date: "Date",
    overall_rating: "Note Globale",
    exec_summary: "Résumé Exécutif",
    factor_analysis: "Analyse Stratégique à 5 Facteurs",
    expert_commentary: "Commentaire d'Expert",
    roadmap: "Feuille de Route Stratégique",
    download_btn: "Télécharger",
    generating: "Génération...",
    reset_btn: "Réinitialiser",
    disclaimer: "Généré par FS Pro | Température 0.0 (Mode Précision)",
    industries: {
      'AI/Data': 'IA/Données',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Santé',
      'Clean Energy': 'Énergie Propre',
      'Aerospace/Manufacturing': 'Industrie',
      'Content/Media': 'Médias',
      'Civil/Construction': 'Génie civil',
      'General/Other': 'Général'
    },
    comments: {
      tech: "Due Diligence Technique",
      market: "Stratégie de Marché",
      fin: "Prévisions Financières",
      risk: "Risque et Conformité"
    }
  },
  es: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Herramienta de Evaluación Estratégica",
    hero_badge: "Due Diligence Profesional",
    hero_title: "Viabilidad Comercial",
    hero_highlight: "Informe de Inteligencia",
    hero_desc: "Configuramos la temperatura de la IA en 0.0 para proporcionar resultados de evaluación cuantitativa consistentes y objetivos.",
    label_industry: "1. Seleccionar Sector",
    label_upload: "2. Subir Documento",
    tab_file: "Archivo",
    tab_text: "Texto",
    drop_title: "Suelte su plan de negocios aquí",
    drop_desc: "Soporta PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Pegue el contenido principal aquí...",
    btn_analyze: "Generar Informe",
    analyzing_title: "Analizando Plan",
    report_title: "Informe de Viabilidad (Confidencial)",
    report_date: "Fecha",
    overall_rating: "Calificación General",
    exec_summary: "Resumen Ejecutivo",
    factor_analysis: "Análisis Estratégico de 5 Factores",
    expert_commentary: "Comentario de Expertos",
    roadmap: "Hoja de Ruta Estratégica",
    download_btn: "Descargar Informe",
    generating: "Generando...",
    reset_btn: "Reiniciar",
    disclaimer: "Generado por FS Pro | Temperatura 0.0 (Modo Precisión)",
    industries: {
      'AI/Data': 'IA/Datos',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Salud',
      'Clean Energy': 'Energía Limpia',
      'Aerospace/Manufacturing': 'Manufactura',
      'Content/Media': 'Medios',
      'Civil/Construction': 'Construcción',
      'General/Other': 'General'
    },
    comments: {
      tech: "Due Diligence Técnica",
      market: "Estrategia de Mercado",
      fin: "Proyección Financiera",
      risk: "Riesgo y Cumplimiento"
    }
  },
  it: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strumento di Valutazione Strategica",
    hero_badge: "Due Diligence Professionale",
    hero_title: "Fattibilità Aziendale",
    hero_highlight: "Rapporto di Intelligence",
    hero_desc: "Impostiamo la temperatura dell'IA a 0.0 per fornire risultati di valutazione quantitativa coerenti e obiettivi.",
    label_industry: "1. Seleziona Settore",
    label_upload: "2. Carica Documento",
    tab_file: "File",
    tab_text: "Testo",
    drop_title: "Rilascia qui il tuo business plan",
    drop_desc: "Supporta PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Incolla qui il contenuto principale...",
    btn_analyze: "Genera Rapporto",
    analyzing_title: "Analisi in corso",
    report_title: "Rapporto di Fattibilità (Riservato)",
    report_date: "Data",
    overall_rating: "Valutazione Generale",
    exec_summary: "Sintesi Esecutiva",
    factor_analysis: "Analisi Strategica a 5 Fattori",
    expert_commentary: "Commento dell'Esperto",
    roadmap: "Roadmap Strategica",
    download_btn: "Scarica",
    generating: "Generazione...",
    reset_btn: "Resetta",
    disclaimer: "Generato da FS Pro | Temperatura 0.0 (Modalità Precisione)",
    industries: {
      'AI/Data': 'IA/Dati',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Salute',
      'Clean Energy': 'Energia Pulita',
      'Aerospace/Manufacturing': 'Manifattura',
      'Content/Media': 'Media',
      'Civil/Construction': 'Costruzioni',
      'General/Other': 'Generale'
    },
    comments: {
      tech: "Due Diligence Tecnica",
      market: "Strategia di Mercato",
      fin: "Proiezione Finanziaria",
      risk: "Rischio e Conformità"
    }
  },
  ru: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Инструмент стратегической оценки",
    hero_badge: "Профессиональный Due Diligence",
    hero_title: "Анализ эффективности",
    hero_highlight: "Бизнес-отчет",
    hero_desc: "Мы устанавливаем температуру ИИ на 0.0 для обеспечения последовательных и объективных количественных результатов оценки.",
    label_industry: "1. Выберите отрасль",
    label_upload: "2. Загрузите документ",
    tab_file: "Файл",
    tab_text: "Текст",
    drop_title: "Перетащите бизнес-план сюда",
    drop_desc: "Поддержка PDF, TXT, MD (Макс 10МБ)",
    text_placeholder: "Вставьте основное содержание здесь...",
    btn_analyze: "Создать отчет",
    analyzing_title: "Анализ бизнес-плана",
    report_title: "Отчет о целесообразности (Конфиденциально)",
    report_date: "Дата",
    overall_rating: "Общий рейтинг",
    exec_summary: "Резюме для руководства",
    factor_analysis: "Стратегический анализ (5 факторов)",
    expert_commentary: "Комментарий эксперта",
    roadmap: "Стратегическая дорожная карта",
    download_btn: "Скачать",
    generating: "Создание...",
    reset_btn: "Сброс",
    disclaimer: "Создано FS Pro | Температура 0.0 (Режим точности)",
    industries: {
      'AI/Data': 'ИИ/Данные',
      'Blockchain/Fintech': 'Финтех',
      'Bio/Healthcare': 'Био/Здоровье',
      'Clean Energy': 'Энергетика',
      'Aerospace/Manufacturing': 'Производство',
      'Content/Media': 'Медиа',
      'Civil/Construction': 'Строительство',
      'General/Other': 'Общее'
    },
    comments: {
      tech: "Технический аудит",
      market: "Рыночная стратегия",
      fin: "Финансовый прогноз",
      risk: "Риски и соответствие"
    }
  }
};
