import React, { useState, useRef, useEffect } from 'react';
import {
  CheckCircle, AlertCircle, TrendingUp, Zap, Loader2,
  Briefcase, File as FileIcon, RefreshCw, Download,
  Bookmark, Layers, Globe, ChevronDown, Printer, Upload
} from 'lucide-react';
import {
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  ResponsiveContainer
} from 'recharts';

/**
 * GEMINI API CONFIGURATION
 * API Key is managed in App state
 */

// --- Types & Interfaces ---

type LanguageCode = 'en' | 'ko' | 'ja' | 'zh' | 'de' | 'fr' | 'it' | 'es' | 'ru';
type IndustryType = 'AI/Data' | 'Blockchain/Fintech' | 'Bio/Healthcare' | 'Clean Energy' | 'Aerospace/Manufacturing' | 'Content/Media' | 'General/Other';

interface EvaluationResult {
  businessName: string;
  summary: string;
  totalScore: number;
  dimensions: {
    id: string;
    name: string;
    score: number;
    grade: string;
    weight: number;
    reasoning: string;
    improvements: string;
  }[];
  expertCommentary: {
    technical: string;
    market: string;
    financial: string;
    policy: string;
  };
  recommendations: string[];
}

// --- Translations ---
const TRANSLATIONS = {
  en: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strategic Business Assessment Tool",
    hero_badge: "Professional Due Diligence",
    hero_title: "Business Feasibility",
    hero_highlight: "Intelligence Report",
    hero_desc: "Get consistent, objective evaluations. We set the AI temperature to 0.0 for reliable, repeatable scoring based on strict McKinsey-style rubrics.",
    label_industry: "1. Select Industry Sector",
    label_upload: "2. Upload Document",
    tab_file: "File Upload",
    tab_text: "Direct Text",
    drop_title: "Drop your Business Plan here",
    drop_desc: "Supports PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Paste the core content of your business plan here...",
    btn_analyze: "Generate Expert Report",
    analyzing_title: "Analyzing Business Plan",
    report_title: "Confidential Feasibility Report",
    report_date: "Date",
    overall_rating: "Overall Rating",
    exec_summary: "Executive Summary",
    factor_analysis: "5-Factor Strategic Analysis",
    expert_commentary: "Expert Commentary",
    roadmap: "Strategic Roadmap & Action Plan",
    download_btn: "Download Report",
    generating: "Generating...",
    reset_btn: "Reset",
    disclaimer: "Generated by FS Pro | Temperature 0.0 (Deterministic Mode)",
    industries: {
      'AI/Data': 'AI & Data',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Health',
      'Clean Energy': 'Clean Energy',
      'Aerospace/Manufacturing': 'Manufacturing',
      'Content/Media': 'Content/Media',
      'General/Other': 'General'
    },
    comments: {
      tech: "Technical Due Diligence",
      market: "Market Strategy",
      fin: "Financial Projection",
      risk: "Risk & Compliance"
    }
  },
  ko: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "전략적 사업성 평가 솔루션",
    hero_badge: "전문가급 기업 실사(Due Diligence)",
    hero_title: "사업 타당성 분석",
    hero_highlight: "인텔리전스 리포트",
    hero_desc: "AI의 창의성 변수(Temperature)를 0으로 제어하여, 언제나 일관성 있고 객관적인 정량 평가 결과를 제공합니다.",
    label_industry: "1. 산업 분야 선택",
    label_upload: "2. 문서 업로드",
    tab_file: "파일 업로드",
    tab_text: "텍스트 입력",
    drop_title: "사업계획서 파일을 이곳에 놓으세요",
    drop_desc: "PDF, TXT, MD 지원 (최대 10MB)",
    text_placeholder: "사업계획서의 핵심 내용을 이곳에 붙여넣으세요...",
    btn_analyze: "전문가 분석 리포트 생성",
    analyzing_title: "사업계획서 심층 분석 중",
    report_title: "사업성 평가 보고서 (대외비)",
    report_date: "평가일",
    overall_rating: "종합 평가 등급",
    exec_summary: "경영진 요약 (Executive Summary)",
    factor_analysis: "5대 핵심 요소 전략 분석",
    expert_commentary: "전문가 심층 코멘트",
    roadmap: "전략적 로드맵 및 실행 계획",
    download_btn: "리포트 다운로드",
    generating: "생성 중...",
    reset_btn: "새로운 분석",
    disclaimer: "FS Pro 생성 자료 | Temperature 0.0 (정밀 분석 모드)",
    industries: {
      'AI/Data': 'AI/데이터',
      'Blockchain/Fintech': '핀테크/블록체인',
      'Bio/Healthcare': '바이오/헬스',
      'Clean Energy': '클린 에너지',
      'Aerospace/Manufacturing': '제조/항공',
      'Content/Media': '콘텐츠/미디어',
      'General/Other': '일반/기타'
    },
    comments: {
      tech: "기술성 실사 (Tech DD)",
      market: "시장 진입 전략",
      fin: "재무 건전성 및 ROI",
      risk: "규제 및 리스크 관리"
    }
  },
  ja: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "戦略的事業性評価ツール",
    hero_badge: "プロフェッショナル・デューデリジェンス",
    hero_title: "事業妥当性分析",
    hero_highlight: "インテリジェンス・レポート",
    hero_desc: "AIの創造性パラメータ（Temperature）を0に設定し、常に一貫性のある客観的な定量評価結果を提供します。",
    label_industry: "1. 産業分野の選択",
    label_upload: "2. ドキュメントのアップロード",
    tab_file: "ファイル",
    tab_text: "テキスト入力",
    drop_title: "ここに事業計画書をドロップ",
    drop_desc: "PDF, TXT, MD 対応 (最大 10MB)",
    text_placeholder: "事業計画書の核心内容をここに貼り付けてください...",
    btn_analyze: "専門家レポートを作成",
    analyzing_title: "事業計画書を分析中",
    report_title: "事業性評価レポート (社外秘)",
    report_date: "日付",
    overall_rating: "総合評価",
    exec_summary: "エグゼクティブ・サマリー",
    factor_analysis: "5大要素 戦略分析",
    expert_commentary: "専門家の解説",
    roadmap: "戦略的ロードマップ & アクションプラン",
    download_btn: "レポートをダウンロード",
    generating: "作成中...",
    reset_btn: "リセット",
    disclaimer: "FS Proにより生成 | Temperature 0.0 (精密分析モード)",
    industries: {
      'AI/Data': 'AI/データ',
      'Blockchain/Fintech': 'フィンテック',
      'Bio/Healthcare': 'バイオ/ヘルス',
      'Clean Energy': 'クリーンエネ',
      'Aerospace/Manufacturing': '製造/航空',
      'Content/Media': 'コンテンツ',
      'General/Other': '一般/その他'
    },
    comments: {
      tech: "技術デューデリジェンス",
      market: "市場参入戦略",
      fin: "財務予測 & ROI",
      risk: "リスクとコンプライアンス"
    }
  },
  zh: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "战略商业评估工具",
    hero_badge: "专业尽职调查",
    hero_title: "商业可行性",
    hero_highlight: "智能分析报告",
    hero_desc: "将AI的创造性参数（Temperature）设置为0，以提供始终如一且客观的定量评估结果。",
    label_industry: "1. 选择行业领域",
    label_upload: "2. 上传文档",
    tab_file: "文件上传",
    tab_text: "直接输入",
    drop_title: "在此处拖放您的商业计划书",
    drop_desc: "支持 PDF, TXT, MD (最大 10MB)",
    text_placeholder: "在此粘贴商业计划书的核心内容...",
    btn_analyze: "生成专家报告",
    analyzing_title: "正在分析商业计划",
    report_title: "可行性评估报告 (机密)",
    report_date: "日期",
    overall_rating: "综合评分",
    exec_summary: "执行摘要 (Executive Summary)",
    factor_analysis: "五维战略分析",
    expert_commentary: "专家点评",
    roadmap: "战略路线图与行动计划",
    download_btn: "下载报告",
    generating: "生成中...",
    reset_btn: "重置",
    disclaimer: "由 FS Pro 生成 | Temperature 0.0 (精密分析模式)",
    industries: {
      'AI/Data': '人工智能/数据',
      'Blockchain/Fintech': '金融科技',
      'Bio/Healthcare': '生物医疗',
      'Clean Energy': '清洁能源',
      'Aerospace/Manufacturing': '制造/航空',
      'Content/Media': '内容/媒体',
      'General/Other': '通用/其他'
    },
    comments: {
      tech: "技术尽职调查",
      market: "市场进入策略",
      fin: "财务预测与回报",
      risk: "风险与合规"
    }
  },
  de: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strategisches Geschäftsbewertungstool",
    hero_badge: "Professionelle Due Diligence",
    hero_title: "Geschäftliche Machbarkeit",
    hero_highlight: "Intelligenzbericht",
    hero_desc: "Wir setzen die AI-Temperatur auf 0,0, um konsistente und objektive quantitative Bewertungsergebnisse zu gewährleisten.",
    label_industry: "1. Industriezweig wählen",
    label_upload: "2. Dokument hochladen",
    tab_file: "Datei-Upload",
    tab_text: "Texteingabe",
    drop_title: "Businessplan hier ablegen",
    drop_desc: "Unterstützt PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Fügen Sie hier den Kerninhalt Ihres Businessplans ein...",
    btn_analyze: "Expertenbericht erstellen",
    analyzing_title: "Businessplan wird analysiert",
    report_title: "Vertraulicher Machbarkeitsbericht",
    report_date: "Datum",
    overall_rating: "Gesamtbewertung",
    exec_summary: "Management-Zusammenfassung",
    factor_analysis: "Strategische 5-Faktoren-Analyse",
    expert_commentary: "Expertenkommentar",
    roadmap: "Strategische Roadmap",
    download_btn: "Bericht herunterladen",
    generating: "Erzeugen...",
    reset_btn: "Zurücksetzen",
    disclaimer: "Generiert von FS Pro | Temperature 0.0 (Präzisionsmodus)",
    industries: {
      'AI/Data': 'KI/Daten',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Gesundheit',
      'Clean Energy': 'Saubere Energie',
      'Aerospace/Manufacturing': 'Fertigung',
      'Content/Media': 'Medien',
      'General/Other': 'Allgemein'
    },
    comments: {
      tech: "Technische Due Diligence",
      market: "Markteintrittsstrategie",
      fin: "Finanzprognose",
      risk: "Risiko & Compliance"
    }
  },
  fr: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Outil d'évaluation stratégique",
    hero_badge: "Due Diligence Professionnelle",
    hero_title: "Faisabilité Commerciale",
    hero_highlight: "Rapport d'Intelligence",
    hero_desc: "Nous réglons la température de l'IA sur 0,0 pour garantir des résultats d'évaluation quantitative cohérents et objectifs.",
    label_industry: "1. Sélectionner le secteur",
    label_upload: "2. Télécharger le document",
    tab_file: "Fichier",
    tab_text: "Texte",
    drop_title: "Déposez votre plan d'affaires ici",
    drop_desc: "Supporte PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Collez ici le contenu principal...",
    btn_analyze: "Générer le rapport",
    analyzing_title: "Analyse en cours",
    report_title: "Rapport de Faisabilité (Confidentiel)",
    report_date: "Date",
    overall_rating: "Note Globale",
    exec_summary: "Résumé Exécutif",
    factor_analysis: "Analyse Stratégique à 5 Facteurs",
    expert_commentary: "Commentaire d'Expert",
    roadmap: "Feuille de Route Stratégique",
    download_btn: "Télécharger",
    generating: "Génération...",
    reset_btn: "Réinitialiser",
    disclaimer: "Généré par FS Pro | Température 0.0 (Mode Précision)",
    industries: {
      'AI/Data': 'IA/Données',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Santé',
      'Clean Energy': 'Énergie Propre',
      'Aerospace/Manufacturing': 'Industrie',
      'Content/Media': 'Médias',
      'General/Other': 'Général'
    },
    comments: {
      tech: "Due Diligence Technique",
      market: "Stratégie de Marché",
      fin: "Prévisions Financières",
      risk: "Risque et Conformité"
    }
  },
  es: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Herramienta de Evaluación Estratégica",
    hero_badge: "Due Diligence Profesional",
    hero_title: "Viabilidad Comercial",
    hero_highlight: "Informe de Inteligencia",
    hero_desc: "Configuramos la temperatura de la IA en 0.0 para proporcionar resultados de evaluación cuantitativa consistentes y objetivos.",
    label_industry: "1. Seleccionar Sector",
    label_upload: "2. Subir Documento",
    tab_file: "Archivo",
    tab_text: "Texto",
    drop_title: "Suelte su plan de negocios aquí",
    drop_desc: "Soporta PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Pegue el contenido principal aquí...",
    btn_analyze: "Generar Informe",
    analyzing_title: "Analizando Plan",
    report_title: "Informe de Viabilidad (Confidencial)",
    report_date: "Fecha",
    overall_rating: "Calificación General",
    exec_summary: "Resumen Ejecutivo",
    factor_analysis: "Análisis Estratégico de 5 Factores",
    expert_commentary: "Comentario de Expertos",
    roadmap: "Hoja de Ruta Estratégica",
    download_btn: "Descargar Informe",
    generating: "Generando...",
    reset_btn: "Reiniciar",
    disclaimer: "Generado por FS Pro | Temperatura 0.0 (Modo Precisión)",
    industries: {
      'AI/Data': 'IA/Datos',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Salud',
      'Clean Energy': 'Energía Limpia',
      'Aerospace/Manufacturing': 'Manufactura',
      'Content/Media': 'Medios',
      'General/Other': 'General'
    },
    comments: {
      tech: "Due Diligence Técnica",
      market: "Estrategia de Mercado",
      fin: "Proyección Financiera",
      risk: "Riesgo y Cumplimiento"
    }
  },
  it: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Strumento di Valutazione Strategica",
    hero_badge: "Due Diligence Professionale",
    hero_title: "Fattibilità Aziendale",
    hero_highlight: "Rapporto di Intelligence",
    hero_desc: "Impostiamo la temperatura dell'IA a 0.0 per fornire risultati di valutazione quantitativa coerenti e obiettivi.",
    label_industry: "1. Seleziona Settore",
    label_upload: "2. Carica Documento",
    tab_file: "File",
    tab_text: "Testo",
    drop_title: "Rilascia qui il tuo business plan",
    drop_desc: "Supporta PDF, TXT, MD (Max 10MB)",
    text_placeholder: "Incolla qui il contenuto principale...",
    btn_analyze: "Genera Rapporto",
    analyzing_title: "Analisi in corso",
    report_title: "Rapporto di Fattibilità (Riservato)",
    report_date: "Data",
    overall_rating: "Valutazione Generale",
    exec_summary: "Sintesi Esecutiva",
    factor_analysis: "Analisi Strategica a 5 Fattori",
    expert_commentary: "Commento dell'Esperto",
    roadmap: "Roadmap Strategica",
    download_btn: "Scarica",
    generating: "Generazione...",
    reset_btn: "Resetta",
    disclaimer: "Generato da FS Pro | Temperatura 0.0 (Modalità Precisione)",
    industries: {
      'AI/Data': 'IA/Dati',
      'Blockchain/Fintech': 'Fintech',
      'Bio/Healthcare': 'Bio/Salute',
      'Clean Energy': 'Energia Pulita',
      'Aerospace/Manufacturing': 'Manifattura',
      'Content/Media': 'Media',
      'General/Other': 'Generale'
    },
    comments: {
      tech: "Due Diligence Tecnica",
      market: "Strategia di Mercato",
      fin: "Proiezione Finanziaria",
      risk: "Rischio e Conformità"
    }
  },
  ru: {
    app_name: "FS",
    app_sub: "Pro",
    app_desc: "Инструмент стратегической оценки",
    hero_badge: "Профессиональный Due Diligence",
    hero_title: "Анализ эффективности",
    hero_highlight: "Бизнес-отчет",
    hero_desc: "Мы устанавливаем температуру ИИ на 0.0 для обеспечения последовательных и объективных количественных результатов оценки.",
    label_industry: "1. Выберите отрасль",
    label_upload: "2. Загрузите документ",
    tab_file: "Файл",
    tab_text: "Текст",
    drop_title: "Перетащите бизнес-план сюда",
    drop_desc: "Поддержка PDF, TXT, MD (Макс 10МБ)",
    text_placeholder: "Вставьте основное содержание здесь...",
    btn_analyze: "Создать отчет",
    analyzing_title: "Анализ бизнес-плана",
    report_title: "Отчет о целесообразности (Конфиденциально)",
    report_date: "Дата",
    overall_rating: "Общий рейтинг",
    exec_summary: "Резюме для руководства",
    factor_analysis: "Стратегический анализ (5 факторов)",
    expert_commentary: "Комментарий эксперта",
    roadmap: "Стратегическая дорожная карта",
    download_btn: "Скачать",
    generating: "Создание...",
    reset_btn: "Сброс",
    disclaimer: "Создано FS Pro | Температура 0.0 (Режим точности)",
    industries: {
      'AI/Data': 'ИИ/Данные',
      'Blockchain/Fintech': 'Финтех',
      'Bio/Healthcare': 'Био/Здоровье',
      'Clean Energy': 'Энергетика',
      'Aerospace/Manufacturing': 'Производство',
      'Content/Media': 'Медиа',
      'General/Other': 'Общее'
    },
    comments: {
      tech: "Технический аудит",
      market: "Рыночная стратегия",
      fin: "Финансовый прогноз",
      risk: "Риски и соответствие"
    }
  }
};

const LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
];

// --- Main Application Component ---

export default function App() {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [apiKey, setApiKey] = useState('');
  const [tempApiKey, setTempApiKey] = useState('');
  const [temperature, setTemperature] = useState<number>(0.0);
  const [selectedIndustry, setSelectedIndustry] = useState<IndustryType>('General/Other');
  const [language, setLanguage] = useState<LanguageCode>('en');
  const [file, setFile] = useState<File | null>(null);
  const [textInput, setTextInput] = useState<string>('');
  const [inputType, setInputType] = useState<'file' | 'text'>('file');
  const [result, setResult] = useState<EvaluationResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isLangMenuOpen, setIsLangMenuOpen] = useState(false);
  const [libStatus, setLibStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const langMenuRef = useRef<HTMLDivElement>(null);

  // Load external scripts for PDF generation with Promise control
  useEffect(() => {
    const loadScript = (src: string) => {
      return new Promise((resolve, reject) => {
        if (document.querySelector(`script[src="${src}"]`)) {
          resolve(true);
          return;
        }
        const script = document.createElement('script');
        script.src = src;
        script.async = true;
        script.onload = () => resolve(true);
        script.onerror = () => reject(false);
        document.body.appendChild(script);
      });
    };

    Promise.all([
      loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js'),
      loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js')
    ])
      .then(() => setLibStatus('ready'))
      .catch(() => setLibStatus('error'));
  }, []);

  // Handle outside click to close language menu
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (langMenuRef.current && !langMenuRef.current.contains(event.target as Node)) {
        setIsLangMenuOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  // --- Handlers ---

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setError(null);
    }
  };

  const handleAnalyze = async () => {
    if (inputType === 'file' && !file) {
      setError("Please upload a file.");
      return;
    }
    if (inputType === 'text' && textInput.length < 50) {
      setError("Please enter enough text (min 50 chars).");
      return;
    }

    setStep(2);
    setError(null);

    try {
      let contentPart: any = {};

      if (inputType === 'text') {
        contentPart = { text: textInput };
      } else if (file) {
        if (file.type === 'application/pdf') {
          const base64Data = await fileToBase64(file);
          contentPart = {
            inlineData: {
              mimeType: "application/pdf",
              data: base64Data
            }
          };
        } else if (file.type === 'text/plain' || file.name.endsWith('.md') || file.name.endsWith('.txt')) {
          const textData = await fileToText(file);
          contentPart = { text: textData };
        } else {
          throw new Error("Browser only supports direct PDF/TXT/MD analysis.");
        }
      }

      // Dynamic Prompt based on Language
      const selectedLangName = LANGUAGES.find(l => l.code === language)?.name || 'English';

      const systemPrompt = `
        You are a Senior Consultant at a top-tier firm (McKinsey/BCG) specializing in ${selectedIndustry}.
        Analyze the provided business plan based on "Business Feasibility Theory" and "Industry Evaluation Models".

        [CRITICAL INSTRUCTION]
        1. **CONSISTENCY**: You MUST act deterministically. The same input should yield the same scores.
        2. **LANGUAGE**: You MUST generate the entire JSON response content in **${selectedLangName}**.
        3. **SCORING RUBRIC**:
           - **S (90-100)**: Global innovation, verified patent, signed contracts > $1M.
           - **A (80-89)**: Clear differentiation, prototype ready, LOI secured.
           - **B (70-79)**: Standard solution, growing market, theoretical MVP.
           - **C (60-69)**: High competition, weak moat, unverified financials.
           - **D (0-59)**: Fatal flaw in logic, shrinking market, regulatory ban.

        [Output JSON Schema]
        Return ONLY valid JSON. No markdown.
        {
          "businessName": "Extracted Project Name",
          "summary": "Executive Summary in ${selectedLangName} (3-5 sentences)",
          "totalScore": 0-100 (Integer, Calculated based on weights),
          "dimensions": [
            { 
              "id": "tech", "name": "Translated Name of 'Technology' in ${selectedLangName}", "score": 0-100, "grade": "S/A/B/C/D", "weight": 0.3, 
              "reasoning": "Rationale in ${selectedLangName}", "improvements": "Action items in ${selectedLangName}" 
            },
            { "id": "market", "name": "Translated Name of 'Market' in ${selectedLangName}", "score": 0-100, "grade": "S/A/B/C/D", "weight": 0.25, "reasoning": "...", "improvements": "..." },
            { "id": "finance", "name": "Translated Name of 'Finance' in ${selectedLangName}", "score": 0-100, "grade": "S/A/B/C/D", "weight": 0.2, "reasoning": "...", "improvements": "..." },
            { "id": "biz", "name": "Translated Name of 'Biz Model' in ${selectedLangName}", "score": 0-100, "grade": "S/A/B/C/D", "weight": 0.15, "reasoning": "...", "improvements": "..." },
            { "id": "risk", "name": "Translated Name of 'Risk' in ${selectedLangName}", "score": 0-100, "grade": "S/A/B/C/D", "weight": 0.1, "reasoning": "...", "improvements": "..." }
          ],
          "expertCommentary": {
            "technical": "Tech Due Diligence in ${selectedLangName}",
            "market": "GTM Strategy in ${selectedLangName}",
            "financial": "Financial Outlook in ${selectedLangName}",
            "policy": "Regulation Check in ${selectedLangName}"
          },
          "recommendations": ["Strategy 1 in ${selectedLangName}", "Strategy 2 in ${selectedLangName}", "Strategy 3 in ${selectedLangName}"]
        }
      `;

      const response = await callGeminiAPI(systemPrompt, contentPart);
      const jsonText = response.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsedResult = JSON.parse(jsonText);

      setResult(parsedResult);
      setStep(3);

    } catch (err: any) {
      console.error(err);
      setError(err.message || "Analysis failed. Please try again.");
      setStep(1);
    }
  };

  const handleReset = () => {
    setFile(null);
    setTextInput('');
    setResult(null);
    setStep(1);
    setError(null);
  };

  // --- Helpers ---
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.split(',')[1];
        resolve(base64);
      };
      reader.onerror = error => reject(error);
    });
  };

  const fileToText = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsText(file);
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = error => reject(error);
    });
  };

  const callGeminiAPI = async (systemPrompt: string, contentPart: any) => {
    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [{
              parts: [
                { text: "Analyze this business plan and output valid JSON." },
                contentPart
              ]
            }],
            systemInstruction: {
              parts: [{ text: systemPrompt }]
            },
            generationConfig: {
              responseMimeType: "application/json",
              temperature: temperature,
            }
          }),
        }
      );

      if (!response.ok) {
        throw new Error(`API Error: ${response.statusText}`);
      }

      const data = await response.json();
      return data.candidates[0].content.parts[0].text;
    } catch (error) {
      throw error;
    }
  };

  const t = TRANSLATIONS[language];

  return (
    <div className="min-h-screen bg-slate-100 font-sans text-slate-800 print:bg-white">
      {/* App Navigation Bar */}
      <header className="bg-slate-900 border-b border-slate-800 sticky top-0 z-50 shadow-lg print:hidden">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-gradient-to-br from-indigo-500 to-blue-600 rounded-lg flex items-center justify-center text-white font-bold shadow-inner">
              <TrendingUp className="w-5 h-5" />
            </div>
            <h1 className="text-xl font-bold text-white tracking-wide">
              {t.app_name} <span className="text-indigo-400 font-light">{t.app_sub}</span>
            </h1>
          </div>

          <div className="flex items-center gap-4">
            <div className="hidden md:block text-xs font-medium text-slate-400 uppercase tracking-widest">
              {t.app_desc}
            </div>
            {/* Language Selector */}
            <div className="relative" ref={langMenuRef}>
              <button
                onClick={() => setIsLangMenuOpen(!isLangMenuOpen)}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm border transition-all duration-200
                  ${isLangMenuOpen
                    ? 'bg-indigo-600 text-white border-indigo-500 shadow-md ring-2 ring-indigo-200 ring-offset-1 ring-offset-slate-900'
                    : 'bg-slate-800 text-slate-200 border-slate-700 hover:bg-slate-700 hover:border-slate-600'
                  }`}
              >
                <Globe className="w-4 h-4" />
                <span className="font-medium">{LANGUAGES.find(l => l.code === language)?.flag}</span>
                <span className="hidden sm:inline font-medium">{LANGUAGES.find(l => l.code === language)?.name}</span>
                <ChevronDown className={`w-3 h-3 transition-transform duration-200 ${isLangMenuOpen ? 'rotate-180' : ''}`} />
              </button>

              {/* Dropdown Menu */}
              {isLangMenuOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-xl shadow-2xl border border-slate-200 overflow-hidden z-[100] animate-in fade-in slide-in-from-top-2 duration-200">
                  <div className="py-1 max-h-[300px] overflow-y-auto custom-scrollbar">
                    {LANGUAGES.map((lang) => (
                      <button
                        key={lang.code}
                        onClick={() => {
                          setLanguage(lang.code);
                          setIsLangMenuOpen(false);
                        }}
                        className={`w-full text-left px-4 py-3 text-sm flex items-center gap-3 transition-colors
                          ${language === lang.code
                            ? 'bg-indigo-50 text-indigo-700 font-bold border-l-4 border-indigo-600'
                            : 'text-slate-700 hover:bg-slate-50 border-l-4 border-transparent'
                          }
                        `}
                      >
                        <span className="text-lg">{lang.flag}</span>
                        <span>{lang.name}</span>
                        {language === lang.code && <CheckCircle className="w-4 h-4 ml-auto" />}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-12 print:p-0">
        {!apiKey && (
          <div className="max-w-md mx-auto bg-white rounded-xl shadow-lg border border-slate-200 p-8 text-center animate-in fade-in zoom-in duration-300">
            <div className="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-6 text-indigo-600">
              <Zap className="w-8 h-8" />
            </div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">Welcome to FS Pro</h2>
            <p className="text-slate-500 mb-6">
              {language === 'ko' ? '서비스 이용을 위해 Gemini API Key를 입력해주세요.' : 'Please enter your Gemini API Key to continue.'}
            </p>

            <div className="space-y-4 text-left">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Gemini API Key</label>
                <input
                  type="password"
                  value={tempApiKey}
                  onChange={(e) => setTempApiKey(e.target.value)}
                  placeholder="AIzaSy..."
                  className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all"
                />
              </div>

              <button
                onClick={() => {
                  if (tempApiKey.trim().length > 10) {
                    setApiKey(tempApiKey.trim());
                  } else {
                    alert("Please enter a valid API Key");
                  }
                }}
                className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-lg transition-colors flex items-center justify-center gap-2"
              >
                {language === 'ko' ? '시작하기' : 'Start Analysis'} <ChevronDown className="w-4 h-4 rotate-[-90deg]" />
              </button>

              <p className="text-xs text-center text-slate-400 mt-4">
                Get a key from <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer" className="text-indigo-500 hover:underline">Google AI Studio</a>.
              </p>
            </div>
          </div>
        )}

        {apiKey && step === 1 && (
          <UploadSection
            t={t}
            industry={selectedIndustry}
            setIndustry={setSelectedIndustry}
            inputType={inputType}
            setInputType={setInputType}
            file={file}
            handleFileUpload={handleFileUpload}
            textInput={textInput}
            setTextInput={setTextInput}
            error={error}
            onAnalyze={handleAnalyze}
            temperature={temperature}
            setTemperature={setTemperature}
          />
        )}

        {apiKey && step === 2 && (
          <AnalyzingSection industry={selectedIndustry} t={t} />
        )}

        {apiKey && step === 3 && result && (
          <ResultSection
            result={result}
            industry={selectedIndustry}
            onReset={handleReset}
            isDownloading={isDownloading}
            setIsDownloading={setIsDownloading}
            libStatus={libStatus}
            t={t}
          />
        )}
      </main>

      {/* Footer */}
      <div className="py-8 text-center text-slate-400 text-xs print:hidden">
        &copy; 2025 FS Pro. All Rights Reserved. Powered by Gemini.
      </div>
    </div>
  );
}

// --- Sub-Components ---

function UploadSection({
  t, industry, setIndustry, inputType, setInputType,
  file, handleFileUpload, textInput, setTextInput, error, onAnalyze,
  temperature, setTemperature
}: any) {

  const industries: IndustryType[] = [
    'AI/Data', 'Blockchain/Fintech', 'Bio/Healthcare',
    'Clean Energy', 'Aerospace/Manufacturing', 'Content/Media', 'General/Other'
  ];

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-700 space-y-12 max-w-4xl mx-auto print:hidden">
      <div className="text-center space-y-6">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-indigo-900/10 text-indigo-700 rounded-full text-xs font-bold tracking-wider uppercase mb-2 border border-indigo-100">
          <Zap className="w-3 h-3" />
          {t.hero_badge}
        </div>
        <h2 className="text-4xl sm:text-5xl font-extrabold text-slate-900 leading-tight font-serif">
          {t.hero_title} <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-700 to-blue-600">
            {t.hero_highlight}
          </span>
        </h2>
        <p className="text-slate-600 max-w-2xl mx-auto text-lg leading-relaxed">
          {t.hero_desc}
        </p>
      </div>

      <div className="bg-white rounded-3xl shadow-2xl shadow-slate-200 border border-slate-100 overflow-hidden">
        {/* Step 1: Industry */}
        <div className="p-8 border-b border-slate-100 bg-slate-50/50">
          <label className="block text-sm font-bold text-slate-900 mb-4 flex items-center gap-2 uppercase tracking-wide">
            <Briefcase className="w-4 h-4 text-indigo-600" />
            {t.label_industry}
          </label>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {industries.map((ind) => (
              <button
                key={ind}
                onClick={() => setIndustry(ind)}
                className={`px-3 py-3 rounded-xl text-xs font-bold transition-all text-center border-2 truncate
                  ${industry === ind
                    ? 'bg-slate-800 text-white border-slate-800 shadow-lg transform scale-105'
                    : 'bg-white text-slate-500 border-slate-200 hover:border-slate-400 hover:text-slate-700'
                  }`}
              >
                {t.industries[ind]}
              </button>
            ))}
          </div>
        </div>

        {/* Step 2: Input */}
        <div className="p-8">
          <label className="block text-sm font-bold text-slate-900 mb-4 flex items-center gap-2 uppercase tracking-wide">
            <FileIcon className="w-4 h-4 text-indigo-600" />
            {t.label_upload}
          </label>

          <div className="flex border-b border-slate-200 mb-6">
            <button
              onClick={() => setInputType('file')}
              className={`flex items-center gap-2 px-6 py-3 text-sm font-bold border-b-2 transition-colors ${inputType === 'file'
                ? 'border-indigo-600 text-indigo-600'
                : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}
            >
              {t.tab_file}
            </button>
            <button
              onClick={() => setInputType('text')}
              className={`flex items-center gap-2 px-6 py-3 text-sm font-bold border-b-2 transition-colors ${inputType === 'text'
                ? 'border-indigo-600 text-indigo-600'
                : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}
            >
              {t.tab_text}
            </button>
          </div>

          <div className="min-h-[220px]">
            {inputType === 'file' ? (
              <div className="space-y-4">
                <div className="border-2 border-dashed border-slate-300 rounded-2xl p-12 text-center hover:bg-indigo-50/30 hover:border-indigo-300 transition-all group relative cursor-pointer">
                  <input
                    type="file"
                    accept=".pdf,.txt,.md"
                    onChange={handleFileUpload}
                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  />
                  <div className="flex flex-col items-center justify-center space-y-4 pointer-events-none">
                    <div className="w-16 h-16 bg-white text-slate-700 rounded-2xl shadow-sm border border-slate-200 flex items-center justify-center group-hover:scale-110 group-hover:text-indigo-600 transition-all">
                      <Upload className="w-8 h-8" />
                    </div>
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 text-lg">{t.drop_title}</p>
                      <p className="text-sm text-slate-500 font-medium">{t.drop_desc}</p>
                    </div>
                  </div>
                </div>

                {file && (
                  <div className="flex items-center p-4 bg-indigo-50 border border-indigo-100 rounded-xl text-indigo-900 animate-in fade-in slide-in-from-top-2">
                    <FileIcon className="w-5 h-5 mr-3 text-indigo-600" />
                    <span className="font-bold truncate flex-1">{file.name}</span>
                    <span className="text-xs bg-white/60 px-2 py-1 rounded font-mono text-indigo-700">{(file.size / 1024).toFixed(1)} KB</span>
                    <CheckCircle className="w-5 h-5 ml-3 text-emerald-500" />
                  </div>
                )}

                <div className="flex items-start gap-3 text-xs text-slate-500 bg-slate-100 p-4 rounded-xl">
                  <AlertCircle className="w-4 h-4 shrink-0 mt-0.5 text-slate-400" />
                  <p>
                    {t.drop_desc}. (PPT/DOC → PDF)
                  </p>
                </div>
              </div>
            ) : (
              <div className="space-y-2">
                <textarea
                  value={textInput}
                  onChange={(e) => setTextInput(e.target.value)}
                  placeholder={t.text_placeholder}
                  className="w-full h-64 p-5 border border-slate-300 rounded-2xl focus:ring-4 focus:ring-indigo-100 focus:border-indigo-500 transition-all resize-none text-slate-700 leading-relaxed font-mono text-sm"
                />
                <div className="text-right text-xs text-slate-400 font-medium">
                  {textInput.length}
                </div>
              </div>
            )}
          </div>

          {error && (
            <div className="mt-6 p-4 bg-rose-50 text-rose-700 text-sm rounded-xl flex items-center gap-3 border border-rose-100 shadow-sm">
              <AlertCircle className="w-5 h-5 shrink-0" />
              <span className="font-medium">{error}</span>
            </div>
          )}

          {/* Temperature Control */}
          <div className="mt-8 pt-8 border-t border-slate-100">
            <div className="flex items-center justify-between mb-4">
              <label className="text-sm font-bold text-slate-700 flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-500" />
                AI Creativity (Temperature)
              </label>
              <span className="text-xs font-mono font-bold bg-slate-100 px-2 py-1 rounded text-slate-600">
                {temperature.toFixed(1)}
              </span>
            </div>
            <input
              type="range"
              min="0.0"
              max="2.0"
              step="0.1"
              value={temperature}
              onChange={(e) => setTemperature(parseFloat(e.target.value))}
              className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
            />
            <div className="flex justify-between text-[10px] text-slate-400 mt-2 font-medium uppercase tracking-wide">
              <span>Precise (0.0)</span>
              <span>Balanced (1.0)</span>
              <span>Creative (2.0)</span>
            </div>
          </div>

          <button
            onClick={onAnalyze}
            className="w-full mt-8 py-5 bg-slate-900 text-white rounded-xl font-bold text-lg hover:bg-slate-800 transition-all active:scale-[0.99] shadow-xl flex items-center justify-center gap-3 group"
          >
            <Zap className="w-5 h-5 text-yellow-400 group-hover:animate-pulse" />
            {t.btn_analyze}
          </button>
        </div>
      </div>
    </div>
  );
}

function AnalyzingSection({ industry, t }: { industry: string, t: any }) {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 98) return prev;
        return prev + 0.5;
      });
    }, 80);

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="flex flex-col items-center justify-center min-h-[600px] text-center space-y-12 animate-in fade-in duration-700 print:hidden">
      <div className="relative w-40 h-40">
        <svg className="w-full h-full transform -rotate-90">
          <circle
            cx="80"
            cy="80"
            r="70"
            stroke="#e2e8f0"
            strokeWidth="8"
            fill="transparent"
          />
          <circle
            cx="80"
            cy="80"
            r="70"
            stroke="#4f46e5"
            strokeWidth="8"
            fill="transparent"
            strokeDasharray={440}
            strokeDashoffset={440 - (440 * progress) / 100}
            className="transition-all duration-300 ease-linear"
            strokeLinecap="round"
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center flex-col">
          <span className="text-4xl font-black text-slate-800">{Math.round(progress)}%</span>
        </div>
      </div>

      <div className="space-y-4 max-w-lg">
        <h3 className="text-2xl font-bold text-slate-900 font-serif">{t.analyzing_title}</h3>
        <div className="h-8 flex items-center justify-center">
          <p className="text-indigo-600 font-medium animate-pulse">{t.industries[industry]}...</p>
        </div>
      </div>
    </div>
  );
}

// --- Custom Tick Component for Radar Chart ---
const CustomRadarTick = (props: any) => {
  const { x, y, payload } = props;
  const { value } = payload;

  // Try to wrap text if it's too long (simple split by space)
  const words = value.split(' ');

  return (
    <text x={x} y={y} textAnchor="middle" fill="#334155" fontSize={10} fontWeight={700}>
      {words.length > 2 ? (
        <>
          <tspan x={x} dy="-0.5em">{words.slice(0, Math.ceil(words.length / 2)).join(' ')}</tspan>
          <tspan x={x} dy="1.2em">{words.slice(Math.ceil(words.length / 2)).join(' ')}</tspan>
        </>
      ) : (
        value
      )}
    </text>
  );
};


function ResultSection({ result, industry, onReset, isDownloading, setIsDownloading, libStatus, t }: {
  result: EvaluationResult,
  industry: string,
  onReset: () => void,
  isDownloading: boolean,
  setIsDownloading: (val: boolean) => void,
  libStatus: 'loading' | 'ready' | 'error',
  t: any
}) {



  const getGradeStyle = (grade: string) => {
    const styles: Record<string, string> = {
      'S': 'bg-slate-900 text-white border-slate-900',
      'A': 'bg-indigo-900 text-white border-indigo-900',
      'B': 'bg-white text-indigo-900 border-indigo-900',
      'C': 'bg-white text-slate-600 border-slate-400',
      'D': 'bg-white text-rose-600 border-rose-200',
    };
    return styles[grade[0]] || styles['C'];
  };

  const chartData = result.dimensions.map(d => ({
    subject: d.name,
    A: d.score,
    fullMark: 100,
  }));

  const handleDownloadPDF = async () => {
    const html2canvas = (window as any).html2canvas;
    const jsPDF = (window as any).jspdf?.jsPDF;

    // --- CRITICAL FALLBACK MECHANISM ---
    if (!html2canvas || !jsPDF || libStatus !== 'ready') {
      console.warn("PDF libraries missing. Executing browser print fallback.");
      window.print();
      return;
    }

    setIsDownloading(true);

    setTimeout(async () => {
      try {
        const element = document.getElementById('report-section');
        if (!element) throw new Error("Report element not found");

        const canvas = await html2canvas(element, {
          scale: 1.5, // Reduced scale for stability
          useCORS: true,
          logging: false,
          backgroundColor: '#ffffff'
        });

        const imgData = canvas.toDataURL('image/png');
        const imgWidth = 210;
        const pageHeight = 297;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;

        const pdf = new jsPDF('p', 'mm', [imgWidth, Math.max(imgHeight, pageHeight) + 10]);
        pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

        const safeName = result.businessName.replace(/[^a-zA-Z0-9가-힣\s_-]/g, '').trim();
        const fileName = safeName ? `${safeName}_Report.pdf` : 'Report.pdf';

        pdf.save(fileName);

      } catch (error) {
        console.error("PDF Fail:", error);
        // Alert user and triggering fallback print
        alert("PDF 생성에 실패하여 인쇄 모드로 전환합니다. 인쇄 창에서 'PDF로 저장'을 선택해주세요.");
        window.print();
      } finally {
        setIsDownloading(false);
      }
    }, 500);
  };

  return (
    <div className="flex flex-col items-center">
      {/* Report Container - Mimics A4 Paper */}
      <div id="report-section" className="bg-white text-slate-800 w-full max-w-[210mm] min-h-[297mm] shadow-2xl p-10 sm:p-14 relative mx-auto my-8 print:shadow-none print:my-0 print:w-full print:max-w-none">

        {/* Top Decorative Bar */}
        <div className="absolute top-0 left-0 right-0 h-3 bg-slate-900 print:hidden"></div>
        <div className="absolute top-3 right-10 w-24 h-2 bg-indigo-600 print:hidden"></div>

        {/* 1. Report Header */}
        <div className="flex justify-between items-end border-b-2 border-slate-900 pb-6 mb-10 mt-4">
          <div>
            <div className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-2">
              {t.report_title}
            </div>
            <h1 className="text-3xl sm:text-4xl font-serif font-bold text-slate-900 leading-tight">
              {result.businessName}
            </h1>
          </div>
          <div className="text-right hidden sm:block">
            <div className="text-sm font-bold text-indigo-800">{t.industries[industry]}</div>
            <div className="text-xs text-slate-500 mt-1">{new Date().toLocaleDateString()}</div>
          </div>
        </div>

        {/* 2. Executive Dashboard */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12 print:block print:space-y-8">

          {/* Score Card */}
          <div className="lg:col-span-1 bg-slate-50 p-6 border-l-4 border-indigo-900 flex flex-col justify-between print:break-inside-avoid print:mb-8">
            <div>
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4">{t.overall_rating}</h3>
              <div className="flex items-baseline gap-2">
                <span className={`text-6xl font-serif font-black ${result.totalScore >= 80 ? 'text-slate-900' : 'text-slate-700'}`}>
                  {result.totalScore}
                </span>
                <span className="text-xl text-slate-400 font-light">/100</span>
              </div>
            </div>

            <div className="mt-6">
              <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden print:hidden">
                <div
                  className={`h-full ${result.totalScore >= 80 ? 'bg-emerald-600' : result.totalScore >= 60 ? 'bg-indigo-600' : 'bg-amber-500'}`}
                  style={{ width: `${result.totalScore}%` }}
                ></div>
              </div>
              <div className="flex justify-between text-[10px] text-slate-400 mt-1 font-medium">
                <span>Risk</span>
                <span>Stable</span>
                <span>Investable</span>
              </div>
            </div>
          </div>

          {/* Executive Summary Text */}
          <div className="lg:col-span-2 print:break-inside-avoid">
            <h3 className="text-lg font-bold text-slate-900 mb-3 flex items-center gap-2 font-serif">
              <Bookmark className="w-5 h-5 text-indigo-700" />
              {t.exec_summary}
            </h3>
            <p className="text-slate-600 leading-relaxed text-sm sm:text-base text-justify font-serif">
              {result.summary}
            </p>
          </div>
        </div>

        {/* 3. Detailed Analysis (Radar + Factors) */}
        <div className="mb-12 print:break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 font-serif">
            {t.factor_analysis}
          </h3>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-10 print:block">
            {/* Radar Chart - Often problematic in PDF/Print, handled by html2canvas or hidden in print css if needed */}
            <div className="lg:col-span-1 flex items-center justify-center bg-slate-50 rounded-xl py-6 border border-slate-100 print:mb-8">
              <div className="w-full h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart cx="50%" cy="50%" outerRadius="70%" data={chartData}>
                    <PolarGrid stroke="#cbd5e1" />
                    <PolarAngleAxis
                      dataKey="subject"
                      tick={<CustomRadarTick />}
                    />
                    <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                    <Radar
                      name="Score"
                      dataKey="A"
                      stroke="#312e81"
                      strokeWidth={2.5}
                      fill="#4f46e5"
                      fillOpacity={0.15}
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Factor Table */}
            <div className="lg:col-span-2 space-y-5 print:space-y-4">
              {result.dimensions.map((dim) => (
                <div key={dim.id} className="group print:break-inside-avoid">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-3">
                      <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-bold border ${getGradeStyle(dim.grade)}`}>
                        {dim.grade}
                      </div>
                      <div>
                        <span className="font-bold text-slate-900 text-sm block">{dim.name}</span>
                      </div>
                    </div>
                    <span className="text-sm font-bold text-slate-700">{dim.score} pts</span>
                  </div>

                  {/* Insight Box */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pl-11">
                    <div className="text-xs text-slate-600 bg-slate-50 p-2.5 rounded border-l-2 border-indigo-400">
                      <strong className="text-indigo-900 block mb-1">Key Strength</strong>
                      {dim.reasoning}
                    </div>
                    <div className="text-xs text-slate-600 bg-slate-50 p-2.5 rounded border-l-2 border-rose-300">
                      <strong className="text-rose-900 block mb-1">Risk / Improvement</strong>
                      {dim.improvements}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* 4. Expert Commentary Grid */}
        <div className="mb-12 print:break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 font-serif">
            {t.expert_commentary}
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 print:block print:space-y-4">
            <CommentaryBox title={t.comments.tech} content={result.expertCommentary.technical} />
            <CommentaryBox title={t.comments.market} content={result.expertCommentary.market} />
            <CommentaryBox title={t.comments.fin} content={result.expertCommentary.financial} />
            <CommentaryBox title={t.comments.risk} content={result.expertCommentary.policy} />
          </div>
        </div>

        {/* 5. Strategic Recommendations (Roadmap Style) */}
        <div className="print:break-inside-avoid">
          <h3 className="text-lg font-bold text-slate-900 mb-6 border-b border-slate-200 pb-2 font-serif">
            {t.roadmap}
          </h3>
          <div className="space-y-4">
            {result.recommendations.map((rec, idx) => (
              <div key={idx} className="flex gap-4 group print:break-inside-avoid">
                <div className="flex flex-col items-center">
                  <div className="w-8 h-8 rounded-full bg-slate-900 text-white flex items-center justify-center font-bold text-sm shrink-0 border-4 border-white shadow-md z-10 print:bg-black print:text-white print:border-black">
                    {idx + 1}
                  </div>
                  {idx !== result.recommendations.length - 1 && (
                    <div className="w-0.5 h-full bg-slate-200 -my-1 print:bg-slate-400"></div>
                  )}
                </div>
                <div className="bg-slate-50 border border-slate-100 p-4 rounded-xl flex-1 shadow-sm group-hover:shadow-md transition-shadow print:bg-white print:border-slate-300">
                  <p className="text-slate-700 text-sm font-medium leading-relaxed">
                    {rec}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer in Report */}
        <div className="absolute bottom-6 left-10 right-10 flex justify-between text-[9px] text-slate-400 border-t border-slate-100 pt-4 print:hidden">
          <span>{t.disclaimer}</span>
          <span>Confidential & Proprietary</span>
        </div>

      </div>

      {/* Floating Action Bar (Outside PDF) */}
      <div className="sticky bottom-8 flex items-center gap-4 bg-white/90 backdrop-blur-md p-3 rounded-full shadow-xl border border-slate-200 z-50 animate-in slide-in-from-bottom-10 print:hidden" data-html2canvas-ignore>
        <button
          onClick={onReset}
          className="w-10 h-10 flex items-center justify-center rounded-full bg-slate-100 text-slate-600 hover:bg-slate-200 transition-colors"
          title={t.reset_btn}
        >
          <RefreshCw className="w-5 h-5" />
        </button>
        <div className="h-6 w-px bg-slate-300"></div>

        {/* FALLBACK PRINT BUTTON (VISIBLE IF PDF FAILS OR USER PREFERS) */}
        <button
          onClick={() => window.print()}
          className="w-10 h-10 flex items-center justify-center rounded-full bg-slate-100 text-slate-600 hover:bg-slate-200 transition-colors sm:hidden"
          title="Print"
        >
          <Printer className="w-5 h-5" />
        </button>

        <button
          onClick={handleDownloadPDF}
          disabled={isDownloading}
          className="flex items-center gap-2 px-6 py-2 bg-slate-900 text-white rounded-full font-bold hover:bg-slate-800 transition-all shadow-lg active:scale-95 disabled:bg-slate-500"
        >
          {isDownloading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              {t.generating}
            </>
          ) : (
            <>
              <Download className="w-4 h-4" />
              {t.download_btn}
            </>
          )}
        </button>
      </div>
    </div>
  );
}

function CommentaryBox({ title, content }: { title: string, content: string }) {
  return (
    <div className="p-5 border border-slate-200 rounded-lg bg-white shadow-sm hover:border-indigo-200 transition-colors print:break-inside-avoid print:border-slate-300">
      <h4 className="text-xs font-bold text-indigo-900 uppercase tracking-wide mb-3 flex items-center gap-2 print:text-black">
        <Layers className="w-3 h-3" />
        {title}
      </h4>
      <p className="text-xs sm:text-sm text-slate-600 leading-relaxed text-justify print:text-black">
        {content}
      </p>
    </div>
  );
}